#!/usr/bin/env bash
# Install nginx web server on web-01

# Update the package list and install nginx
apt-get update -y
apt-get install -y nginx

# Create a basic HTML file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx service
service nginx restart

exit 0

