#!/usr/bin/env bash

# Check if the private key file 'school' already exists
if [ -f ~/.ssh/school ]; then
    echo "The 'school' private key already exists."
else
    # Generate a new RSA key pair with 4096 bits and passphrase 'betty'
    ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N 'betty'

    if [ $? -eq 0 ]; then
        echo "RSA key pair successfully generated and protected with passphrase 'betty'."
    else
        echo "Failed to generate the RSA key pair."
    fi
fi

