#!/usr/bin/env bash

# Create or edit the SSH client configuration file
touch ~/.ssh/config

# Add configuration to the SSH client file
echo "Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no" > ~/.ssh/config

# Display a success message
echo "SSH client configuration updated successfully."

